using UnityEngine;
using System.Collections;


public class CameraDrag : MonoBehaviour
{
	public Transform target;
	public Vector3 targetOffset;
	public float distance = 5.0f;
	public float maxDistance = 20; 
	public float minDistance = .6f; 
	public float xSpeed = 200.0f;
	public float ySpeed = 200.0f;
	public int yMinLimit = -80;
	public int yMaxLimit = 80; //default 80
	public int zoomRate = 40;
	public float panSpeed = 0.3f;
	public float zoomDampening = 5.0f;
	private float xDeg = 0.0f;
	private float yDeg = 0.0f;
	private float currentDistance;
	private float desiredDistance;
	private Quaternion currentRotation;
	private Quaternion desiredRotation;
	private Quaternion rotation;
	private Vector3 position;
	private float isOrbiting = 0;
	void Start() { Init(); }
	void OnEnable() { Init(); }
	public void Init()
	{
		//If there is no target, creates a temporary target at 'distance' from the cameras current viewpoint
		if (!target)
		{
			GameObject go = new GameObject("Cam Target");
			go.transform.position = transform.position + (transform.forward * distance);
			target = go.transform;
		}
		distance = Vector3.Distance(transform.position, target.position);
		currentDistance = distance;
		desiredDistance = distance;

		position = transform.position;
		rotation = transform.rotation;
		currentRotation = transform.rotation;
		desiredRotation = transform.rotation;
		
		xDeg = Vector3.Angle(Vector3.right, transform.right );
		yDeg = Vector3.Angle(Vector3.up, transform.up );
	}
	/*
	 * Camera logic on LateUpdate to only update after all character movement logic has been handled.
	 */
	void LateUpdate()
	{
		// ZOOM
		if (Input.GetMouseButton(2) && Input.GetKey(KeyCode.LeftAlt) && Input.GetKey(KeyCode.LeftControl))
		{
			desiredDistance -= Input.GetAxis("Mouse Y") * Time.deltaTime * zoomRate*0.125f * Mathf.Abs(desiredDistance);
		}
		//ORBIT
		if (Input.GetMouseButton(2) /*&& Input.GetKey(KeyCode.LeftAlt)*/)
		{
			isOrbiting = 1;
		}
		else {
			isOrbiting = 0;
		}
		
		xDeg += Input.GetAxis("Mouse X") * (xSpeed * isOrbiting) * 0.02f;
		yDeg -= Input.GetAxis("Mouse Y") * (ySpeed * isOrbiting) * 0.02f;
		
		// Clamp the vertical axis for the orbit
		yDeg = ClampAngle(yDeg, yMinLimit, yMaxLimit);
		// set camera rotation
		desiredRotation = Quaternion.Euler(yDeg, xDeg, 0);
		currentRotation = transform.rotation;
		
		rotation = Quaternion.Lerp(currentRotation, desiredRotation, Time.deltaTime * zoomDampening);
		transform.rotation = rotation;
		

	    if (Input.GetMouseButton(1))
	    {
		    target.rotation = transform.rotation;
		    target.Translate(Vector3.right * -Input.GetAxis("Mouse X") * panSpeed);
		    target.Translate(transform.up * -Input.GetAxis("Mouse Y") * panSpeed, Space.World);
	    }
		

		desiredDistance -= Input.GetAxis("Mouse ScrollWheel") * Time.deltaTime * zoomRate * Mathf.Abs(desiredDistance);

		desiredDistance = Mathf.Clamp(desiredDistance, minDistance, maxDistance);

		currentDistance = Mathf.Lerp(currentDistance, desiredDistance, Time.deltaTime * zoomDampening);

		position = target.position - (rotation * Vector3.forward * currentDistance + targetOffset);
		transform.position = position;
	}
	private static float ClampAngle(float angle, float min, float max)
	{
		if (angle < -360)
			angle += 360;
		if (angle > 360)
			angle -= 360;
		return Mathf.Clamp(angle, min, max);
	}

}